//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXeTuDong_KhoaLuanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyThang
    {
        public int MaDangKy { get; set; }
        public string HoTenKH { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<System.DateTime> ThoiGianDangKy { get; set; }
        public Nullable<int> LoaiXe { get; set; }
        public Nullable<int> MaLoaiThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ThoiHan { get; set; }
    
        public virtual LoaiThanhToan LoaiThanhToan { get; set; }
        public virtual LoaiXe LoaiXe1 { get; set; }
    }
}
