//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXeTuDong_KhoaLuanTotNghiep.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBaiGiuXeEntities : DbContext
    {
        public QLBaiGiuXeEntities()
            : base("name=QLBaiGiuXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiDauXe> BaiDauXes { get; set; }
        public virtual DbSet<DangKyThang> DangKyThangs { get; set; }
        public virtual DbSet<LichSuXe> LichSuXes { get; set; }
        public virtual DbSet<LoaiThanhToan> LoaiThanhToans { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<TheXeNgay> TheXeNgays { get; set; }
        public virtual DbSet<TheXeThang> TheXeThangs { get; set; }
        public virtual DbSet<ViTriDauXe> ViTriDauXes { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    }
}
