//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXeTuDong_KhoaLuanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuXe
    {
        public int MaLichSu { get; set; }
        public string LuotVao { get; set; }
        public string LuotRa { get; set; }
        public Nullable<int> MaTheXeNgay { get; set; }
        public Nullable<int> MaTheXeThang { get; set; }
        public Nullable<int> MaThanhToan { get; set; }
    
        public virtual ThanhToan ThanhToan { get; set; }
        public virtual TheXeNgay TheXeNgay { get; set; }
        public virtual TheXeThang TheXeThang { get; set; }
    }
}
