//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXeTuDong_KhoaLuanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhToan()
        {
            this.LichSuXes = new HashSet<LichSuXe>();
            this.TheXeNgays = new HashSet<TheXeNgay>();
            this.TheXeThangs = new HashSet<TheXeThang>();
        }
    
        public int MaThanhToan { get; set; }
        public Nullable<int> MaTheXe { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaLoaiThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXe> LichSuXes { get; set; }
        public virtual LoaiThanhToan LoaiThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheXeNgay> TheXeNgays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheXeThang> TheXeThangs { get; set; }
    }
}
