//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXeTuDong_KhoaLuanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViTriDauXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ViTriDauXe()
        {
            this.TheXeNgays = new HashSet<TheXeNgay>();
        }
    
        public int MaViTri { get; set; }
        public Nullable<int> MaBaiDauXe { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> SoGioDauXe { get; set; }
    
        public virtual BaiDauXe BaiDauXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheXeNgay> TheXeNgays { get; set; }
    }
}
