//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXeTuDong_KhoaLuanTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public string BienSo { get; set; }
        public Nullable<int> MaTheXe { get; set; }
        public Nullable<int> MaLoaiXe { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual LoaiXe LoaiXe { get; set; }
        public virtual TheXeNgay TheXeNgay { get; set; }
    }
}
